title: Maheedhar Attaluri
logo: /assets/images/profilephoto.jpeg
description: Data Alchemist | Bridging the Gap Between Data and Value | AWS Certified Cloud Engineer ðŸš€ðŸ“Š
#show_downloads: true
theme: jekyll-theme-minimal
