title: Maheedhar Attaluri
logo: /assets/images/profilephoto.jpeg
description: Data Alchemist | Bridging the Gap Between Data and Value | AWS Certified Cloud Engineer
## ğŸ“ Wichita, Kansas

ğŸ“ [Phone: +1-3162235472](tel:+1-3162235472)

âœ‰ï¸ [Email: maheedhar.attaluri@outlook.com](mailto: maheedhar.attaluri@outlook.com)

ğŸ”— [LinkedIn: Maheedhar Attaluri](https://www.linkedin.com/in/maheedhar-attaluri-6136b51ab/)

ğŸ‘¨â€ğŸ’» [GitHub: viraniriaz](https://github.com/viraniriaz)
#show_downloads: true
theme: jekyll-theme-minimal
